# Generated by Django 4.2.16 on 2024-11-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_position_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contact_data',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
