# Generated by Django 4.2.16 on 2024-11-10 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_department_eventactivity_eventstatus_institutiontype_and_more'),
        ('users', '0004_remove_employee_contact_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contactdata', verbose_name='Контактные данные')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.department', verbose_name='Подразделение')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee', verbose_name='ID сотрудника-куратора')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название/номер школы')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contactdata', verbose_name='Контактные данные директора')),
                ('institution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.institutiontype', verbose_name='Вид учебного заведения')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contactdata', verbose_name='Контактные данные студента')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('head_contact_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contactdata', verbose_name='Контактные данные руководителя')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='SchoolResponsibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.academicyear', verbose_name='Учебный год')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee', verbose_name='Ответственный')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Ответственный за школу',
                'verbose_name_plural': 'Ответственные за школы',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание предприятия')),
                ('contact_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contactdata', verbose_name='Контактные данные партнера')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.specialty', verbose_name='Специальность'),
        ),
    ]
