# Generated by Django 4.2.16 on 2024-11-10 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_employee_group_school_student_specialty_and_more'),
        ('common', '0002_department_eventactivity_eventstatus_institutiontype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='common.academicyear', verbose_name='Учебный год')),
                ('event_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.eventstatus', verbose_name='Статус мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='MethodicalFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('location', models.FileField(upload_to='methodical_files', verbose_name='Файл')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodical_files', to='users.employee', verbose_name='ID сотрудника')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodical_files', to='users.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Методический файл',
                'verbose_name_plural': 'Методические файлы',
            },
        ),
        migrations.CreateModel(
            name='RelevantMethodicalFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.eventactivity', verbose_name='ID вида деятельности')),
                ('methodical_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.methodicalfile', verbose_name='ID методического файла')),
            ],
            options={
                'verbose_name': 'Релевантный методический файл',
                'verbose_name_plural': 'Релевантные методические файлы',
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participation_points', models.IntegerField(verbose_name='Баллы за участие')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.event', verbose_name='ID мероприятия')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='users.student', verbose_name='ID студента')),
            ],
            options={
                'verbose_name': 'Участник мероприятия',
                'verbose_name_plural': 'Участники мероприятий',
            },
        ),
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to='users.employee', verbose_name='ID сотрудника-организатора')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.event', verbose_name='ID мероприятия')),
            ],
            options={
                'verbose_name': 'Организатор мероприятия',
                'verbose_name_plural': 'Организаторы мероприятий',
            },
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.event', verbose_name='ID мероприятия')),
                ('event_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.eventactivity', verbose_name='ID вида деятельности мероприятия')),
            ],
            options={
                'verbose_name': 'Деталь мероприятия',
                'verbose_name_plural': 'Детали мероприятий',
            },
        ),
    ]
