# Generated by Django 4.2.16 on 2024-12-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название учреждения')),
            ],
            options={
                'verbose_name': 'Образовательное учреждение',
                'verbose_name_plural': 'Образовательные учреждения',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название профессии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание профессии в формате Markdown')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True, verbose_name='Название опроса')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='SurveyScoreVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя параметра')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок при результате')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание при результате')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey', verbose_name='Тестирование')),
            ],
            options={
                'verbose_name': 'Переменная оценки',
                'verbose_name_plural': 'Переменные оценки',
                'unique_together': {('survey', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionPairTypeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=256, verbose_name='Утверждение')),
                ('scoreVariable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyscorevariable', verbose_name='Параметр оценки')),
            ],
            options={
                'verbose_name': 'Утверждение',
                'verbose_name_plural': 'Утверждения',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionPairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statementA', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statementA', to='surveys.surveyquestionpairtypestatement', verbose_name='Утверждение A')),
                ('statementB', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statementB', to='surveys.surveyquestionpairtypestatement', verbose_name='Утверждение B')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Пара вопросов',
                'verbose_name_plural': 'Пары вопросов',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название специальности')),
                ('link', models.URLField(blank=True, max_length=256, null=True, verbose_name='Ссылка на официальный сайт')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.educationalinstitution', verbose_name='Учебное заведение')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='ProfessionSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.profession', verbose_name='Профессия')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специальность профессии',
                'verbose_name_plural': 'Специальности профессий',
            },
        ),
        migrations.CreateModel(
            name='TestResultProfession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.profession', verbose_name='Профессия')),
                ('survey_score_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionSurveyScoreVariable', to='surveys.surveyscorevariable', verbose_name='Параметр оценки опроса')),
            ],
            options={
                'verbose_name': 'Результат теста по профессии',
                'verbose_name_plural': 'Результаты тестов по профессиям',
                'unique_together': {('profession', 'survey_score_variable')},
            },
        ),
    ]
